version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"

  - package-ecosystem: "pip"
    directory: "/apps/studio-api"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps-api)"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/apps/studio-web"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps-web)"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(docker)"
